INSERT INTO "LUGAR" VALUES (1, 'PAIS', 'ESTADOS UNIDOS', 'ESTADOUNIDENSE', NULL);
INSERT INTO "LUGAR" VALUES (2, 'ESTADO', 'CALIFORNIA', NULL, 1);
INSERT INTO "LUGAR" VALUES (3, 'CIUDAD', 'HOLLYWOOD', NULL, 2);
INSERT INTO "LUGAR" VALUES (4, 'CIUDAD', 'LOS ANGELES', NULL, 2);
INSERT INTO "LUGAR" VALUES (5, 'PAIS', 'JAPON', 'JAPONES', NULL);
INSERT INTO "LUGAR" VALUES (6, 'PAIS', 'REINO UNIDO', 'BRITANICO', NULL);
INSERT INTO "LUGAR" VALUES (7, 'PAIS', 'FRANCIA', 'FRANCES', NULL);
INSERT INTO "LUGAR" VALUES (8, 'PAIS', 'CHILE', 'CHILENO', NULL);
