rem / INSERTS /

rem / INSERTS LUGAR /

INSERT INTO LUGAR VALUES (S_LUGAR.NEXTVAL,'PAIS','ESTADOS UNIDOS','ESTADOUNIDENSE',NULL);
INSERT INTO LUGAR VALUES (S_LUGAR.NEXTVAL,'ESTADO','CALIFORNIA',NULL,(SELECT LUGA_ID FROM LUGAR WHERE LUGA_NOMBRE = 'ESTADOS UNIDOS'));
INSERT INTO LUGAR VALUES (S_LUGAR.NEXTVAL,'CIUDAD','HOLLYWOOD',NULL,(SELECT LUGA_ID FROM LUGAR WHERE LUGA_NOMBRE = 'CALIFORNIA' AND LUGA_TIPO = 'ESTADO'));
INSERT INTO LUGAR VALUES (S_LUGAR.NEXTVAL,'CIUDAD','LOS ANGELES',NULL,(SELECT LUGA_ID FROM LUGAR WHERE LUGA_NOMBRE = 'CALIFORNIA' AND LUGA_TIPO = 'ESTADO'));


rem / INSERTS CEREMONIA /

INSERT INTO CEREMONIA VALUES (S_CEREMONIA.NEXTVAL,to_date('20/05/1952','dd/mm/yyyy'),24,'RKO Pantages Theatre',NULL,(SELECT LUGA_ID FROM LUGAR WHERE LUGA_NOMBRE = 'HOLLYWOOD' AND LUGA_TIPO = 'CIUDAD')); 
INSERT INTO CEREMONIA VALUES (S_CEREMONIA.NEXTVAL,to_date('25/05/1985','dd/mm/yyyy'),57,'Dorothy Chandler Pavillion',NULL,(SELECT LUGA_ID FROM LUGAR WHERE LUGA_NOMBRE = 'LOS ANGELES' AND LUGA_TIPO = 'CIUDAD')); 
INSERT INTO CEREMONIA VALUES (S_CEREMONIA.NEXTVAL,to_date('24/05/1986','dd/mm/yyyy'),28,'Dorothy Chandler Pavillion',NULL,(SELECT LUGA_ID FROM LUGAR WHERE LUGA_NOMBRE = 'HOLLYWOOD' AND LUGA_TIPO = 'CIUDAD')); 


rem / INSERTS PREMIO_CATEGORIA /

INSERT INTO PREMIO_CATEGORIA VALUES(S_PREMIO.NEXTVAL,1,'Rama de actuacion del cine.',nt_nombre(t_nombre('Actores',to_date('01/01/1928','dd/mm/YYYY'),NULL)),'Estatuilla',NULL);
INSERT INTO PREMIO_CATEGORIA VALUES(S_PREMIO.NEXTVAL,1,'Rama de guionistas del cine.',nt_nombre(t_nombre('Guionistas',to_date('01/01/1928','dd/mm/YYYY'),NULL)),'Estatuilla',NULL);
INSERT INTO PREMIO_CATEGORIA VALUES(S_PREMIO.NEXTVAL,1,'Rama de direccion del cine.',nt_nombre(t_nombre('Directores',to_date('01/01/1928','dd/mm/YYYY'),NULL)),'Estatuilla',NULL);
INSERT INTO PREMIO_CATEGORIA VALUES(S_PREMIO.NEXTVAL,1,'Rama de produccion del cine.',nt_nombre(t_nombre('Productores',to_date('01/01/1928','dd/mm/YYYY'),NULL)),'Estatuilla',NULL);
INSERT INTO PREMIO_CATEGORIA VALUES(S_PREMIO.NEXTVAL,1,'Rama tecnica del cine.',nt_nombre(t_nombre('Tecnicos',to_date('01/01/1928','dd/mm/YYYY'),NULL)),'Estatuilla',NULL);