rem / INSERTS /

rem / INSERTS LUGAR /

INSERT INTO LUGAR VALUES (S_LUGAR.NEXTVAL,'PAIS','ESTADOS UNIDOS','ESTADOUNIDENSE',NULL);
INSERT INTO LUGAR VALUES (S_LUGAR.NEXTVAL,'ESTADO','CALIFORNIA',NULL,(SELECT LUGA_ID FROM LUGAR WHERE LUGA_NOMBRE = 'ESTADOS UNIDOS'));
INSERT INTO LUGAR VALUES (S_LUGAR.NEXTVAL,'CIUDAD','HOLLYWOOD',NULL,(SELECT LUGA_ID FROM LUGAR WHERE LUGA_NOMBRE = 'CALIFORNIA' AND LUGA_TIPO = 'ESTADO'));
INSERT INTO LUGAR VALUES (S_LUGAR.NEXTVAL,'CIUDAD','LOS ANGELES',NULL,(SELECT LUGA_ID FROM LUGAR WHERE LUGA_NOMBRE = 'CALIFORNIA' AND LUGA_TIPO = 'ESTADO'));
INSERT INTO "LUGAR" VALUES (5, 'PAIS', 'JAPON', 'JAPONES', NULL);
INSERT INTO "LUGAR" VALUES (6, 'PAIS', 'REINO UNIDO', 'BRITANICO', NULL);
INSERT INTO "LUGAR" VALUES (7, 'PAIS', 'FRANCIA', 'FRANCES', NULL);
INSERT INTO "LUGAR" VALUES (8, 'PAIS', 'CHILE', 'CHILENO', NULL);

rem / INSERTS CEREMONIA /

INSERT INTO CEREMONIA VALUES (S_CEREMONIA.NEXTVAL,to_date('20/05/1952','dd/mm/yyyy'),24,'RKO Pantages Theatre',NULL,(SELECT LUGA_ID FROM LUGAR WHERE LUGA_NOMBRE = 'HOLLYWOOD' AND LUGA_TIPO = 'CIUDAD')); 
INSERT INTO CEREMONIA VALUES (S_CEREMONIA.NEXTVAL,to_date('25/05/1985','dd/mm/yyyy'),57,'Dorothy Chandler Pavillion',NULL,(SELECT LUGA_ID FROM LUGAR WHERE LUGA_NOMBRE = 'LOS ANGELES' AND LUGA_TIPO = 'CIUDAD')); 
INSERT INTO CEREMONIA VALUES (S_CEREMONIA.NEXTVAL,to_date('24/05/1986','dd/mm/yyyy'),28,'Dorothy Chandler Pavillion',NULL,(SELECT LUGA_ID FROM LUGAR WHERE LUGA_NOMBRE = 'HOLLYWOOD' AND LUGA_TIPO = 'CIUDAD')); 


rem / INSERTS PREMIO_CATEGORIA /

INSERT INTO PREMIO_CATEGORIA VALUES(S_PREMIO.NEXTVAL,1,'Rama de actuacion del cine.',nt_nombre(t_nombre('Actores',to_date('01/01/1928','dd/mm/YYYY'),NULL)),'Estatuilla',NULL);
INSERT INTO PREMIO_CATEGORIA VALUES(S_PREMIO.NEXTVAL,1,'Rama de guionistas del cine.',nt_nombre(t_nombre('Guionistas',to_date('01/01/1928','dd/mm/YYYY'),NULL)),'Estatuilla',NULL);
INSERT INTO PREMIO_CATEGORIA VALUES(S_PREMIO.NEXTVAL,1,'Rama de direccion del cine.',nt_nombre(t_nombre('Directores',to_date('01/01/1928','dd/mm/YYYY'),NULL)),'Estatuilla',NULL);
INSERT INTO PREMIO_CATEGORIA VALUES(S_PREMIO.NEXTVAL,1,'Rama de produccion del cine.',nt_nombre(t_nombre('Productores',to_date('01/01/1928','dd/mm/YYYY'),NULL)),'Estatuilla',NULL);
INSERT INTO PREMIO_CATEGORIA VALUES(S_PREMIO.NEXTVAL,1,'Rama tecnica del cine.',nt_nombre(t_nombre('Tecnicos',to_date('01/01/1928','dd/mm/YYYY'),NULL)),'Estatuilla',NULL);
INSERT INTO PREMIO_CATEGORIA VALUES(S_PREMIO.NEXTVAL,2,'Division de la produccion referida a los largometrajes, es decir, peliculas de mas de 60 min.',nt_nombre(t_nombre('Largometrajes',to_date('1/1/1928','dd/mm/yyyy'),NULL)),'Estatuilla',4);
INSERT INTO PREMIO_CATEGORIA VALUES(S_PREMIO.NEXTVAL,2,'Division de la produccion referida a los cortometrajes, es decir, peliculas de menos de 60 min.',nt_nombre(t_nombre('Cortometrajes',to_date('1/1/1931','dd/mm/yyyy'),NULL)),'Estatuilla',4);
INSERT INTO PREMIO_CATEGORIA VALUES(S_PREMIO.NEXTVAL,2,'Division de los directores enfocados en la direccion general',nt_nombre(t_nombre('Direccion',to_date('1/1/1928','dd/mm/yyyy'),NULL)),'Estatuilla',3);
INSERT INTO PREMIO_CATEGORIA VALUES(S_PREMIO.NEXTVAL,2,'Division de los actores enfocada en la actuacion',nt_nombre(t_nombre('Actuacion',to_date('1/1/1928','dd/mm/yyyy'),NULL)),'Estatuilla',1);
INSERT INTO PREMIO_CATEGORIA VALUES(S_PREMIO.NEXTVAL,2,'Division de los guionistas enfocada en la escritura',nt_nombre(t_nombre('Escritura',to_date('1/1/1928','dd/mm/yyyy'),NULL)),'Estatuilla',1);
INSERT INTO PREMIO_CATEGORIA VALUES(S_PREMIO.NEXTVAL,2,'Division de los tecnicos enfocada en la fotografia',nt_nombre(t_nombre('Fotografia',to_date('1/1/1928','dd/mm/yyyy'),NULL)),'Estatuilla',5);
INSERT INTO PREMIO_CATEGORIA VALUES(S_PREMIO.NEXTVAL,2,'Division de los directores enfocada a la direccion de arte',nt_nombre(t_nombre('Direccion de Arte',to_date('1/1/1928','dd/mm/yyyy'),NULL)),'Estatuilla',3);
INSERT INTO PREMIO_CATEGORIA VALUES(S_PREMIO.NEXTVAL,2,'Division de los tecnicos enfocada en el sonido',nt_nombre(t_nombre('Sonido',to_date('1/1/1930','dd/mm/yyyy'),NULL)),'Estatuilla',5);
INSERT INTO PREMIO_CATEGORIA VALUES(S_PREMIO.NEXTVAL,2,'Division de los tecnicos enfocada en la musica',nt_nombre(t_nombre('Musica',to_date('1/1/1934','dd/mm/yyyy'),NULL)),'Estatuilla',5);
INSERT INTO PREMIO_CATEGORIA VALUES(S_PREMIO.NEXTVAL,2,'Division de los tecnicos enfocada en la edicion',nt_nombre(t_nombre('Edicion',to_date('1/1/1935','dd/mm/yyyy'),NULL)),'Estatuilla',5);
INSERT INTO PREMIO_CATEGORIA VALUES(S_PREMIO.NEXTVAL,2,'Division de los tecnicos enfocada en los efectos visuales',nt_nombre(t_nombre('Efectos Visuales',to_date('1/1/1939','dd/mm/yyyy'),NULL)),'Estatuilla',5);
INSERT INTO PREMIO_CATEGORIA VALUES(S_PREMIO.NEXTVAL,2,'Division de los productores enfocada en los documentales',nt_nombre(t_nombre('Documentales',to_date('1/1/1934','dd/mm/yyyy'),NULL)),'Estatuilla',4);
INSERT INTO PREMIO_CATEGORIA VALUES(S_PREMIO.NEXTVAL,2,'Division de los tecnicos enfocada en los vestuarios',nt_nombre(t_nombre('Musica',to_date('1/1/1948','dd/mm/yyyy'),NULL)),'Estatuilla',5);
INSERT INTO PREMIO_CATEGORIA VALUES(S_PREMIO.NEXTVAL,2,'Division de los productores enfocada en peliculas extranjeras',nt_nombre(t_nombre('Peliculas Extranjeras',to_date('1/1/1956','dd/mm/yyyy'),NULL)),'Estatuilla',4);
INSERT INTO PREMIO_CATEGORIA VALUES(S_PREMIO.NEXTVAL,2,'Division de los tecnicos enfocada en el maquillaje',nt_nombre(t_nombre('Maquilaje',to_date('1/1/1981','dd/mm/yyyy'),NULL)),'Estatuilla',5);
INSERT INTO PREMIO_CATEGORIA VALUES(S_PREMIO.NEXTVAL,2,'Division de los productores enfocada en las peliculas animadas',nt_nombre(t_nombre('Peliculas Animadas',to_date('1/1/2001','dd/mm/yyyy'),NULL)),'Estatuilla',4);


rem / INSERTS ROL /

INSERT INTO ROL VALUES(S_ROL.NEXTVAL,'DIRECTOR',NULL);
INSERT INTO ROL VALUES(S_ROL.NEXTVAL,'ACTOR PRINCIPAL',NULL);
INSERT INTO ROL VALUES(S_ROL.NEXTVAL,'ACTRIZ PRINCIPAL',NULL);
INSERT INTO ROL VALUES(S_ROL.NEXTVAL,'ACTOR DE REPARTO',NULL);
INSERT INTO ROL VALUES(S_ROL.NEXTVAL,'ACTRIZ DE REPARTO',NULL);
INSERT INTO ROL VALUES(S_ROL.NEXTVAL,'PRODUCTOR',NULL);
INSERT INTO ROL VALUES(S_ROL.NEXTVAL,'MUSICO',NULL);
INSERT INTO ROL VALUES(S_ROL.NEXTVAL,'DIRECTOR ARTE',NULL);
INSERT INTO ROL VALUES(S_ROL.NEXTVAL,'MAQUILLISTA',NULL);
INSERT INTO ROL VALUES(S_ROL.NEXTVAL,'EDITOR',NULL);
INSERT INTO ROL VALUES(S_ROL.NEXTVAL,'VESTUARISTA',NULL);
INSERT INTO ROL VALUES(S_ROL.NEXTVAL,'SONIDISTA',NULL);

rem / INSERTS GENERO /

INSERT INTO GENERO VALUES (S_GENERO.NEXTVAL,'DRAMA',NULL);
INSERT INTO GENERO VALUES (S_GENERO.NEXTVAL,'MUSICAL',NULL);
INSERT INTO GENERO VALUES (S_GENERO.NEXTVAL,'AVENTURA',NULL);
INSERT INTO GENERO VALUES (S_GENERO.NEXTVAL,'BIOGRAFIA',NULL);
INSERT INTO GENERO VALUES (S_GENERO.NEXTVAL,'DRAMA',(SELECT GENE_ID FROM GENERO WHERE GENE_NOMBRE = 'BIOGRAFIA' AND GENE_PADRE IS NULL));
INSERT INTO GENERO VALUES (S_GENERO.NEXTVAL,'MUSICAL',(SELECT GENE_ID FROM GENERO WHERE GENE_NOMBRE = 'DRAMA' AND GENE_PADRE= (SELECT GENE_ID FROM GENERO WHERE GENE_NOMBRE = 'BIOGRAFIA' AND GENE_PADRE IS NULL)));
INSERT INTO GENERO VALUES (S_GENERO.NEXTVAL,'COMEDIA',NULL);
INSERT INTO GENERO VALUES (S_GENERO.NEXTVAL,'MUSICAL',(SELECT GENE_ID FROM GENERO WHERE GENE_NOMBRE = 'COMEDIA' AND GENE_PADRE IS NULL));
INSERT INTO GENERO VALUES (S_GENERO.NEXTVAL,'ROMANCE',(SELECT GENE_ID FROM GENERO WHERE GENE_NOMBRE = 'MUSICAL' AND GENE_PADRE = (SELECT GENE_ID FROM GENERO WHERE GENE_NOMBRE = 'COMEDIA' AND GENE_PADRE IS NULL)));
INSERT INTO GENERO VALUES (S_GENERO.NEXTVAL,'SCI-FI',NULL);
INSERT INTO GENERO VALUES (S_GENERO.NEXTVAL,'THRILLER',(SELECT GENE_ID FROM GENERO WHERE GENE_NOMBRE = 'DRAMA' AND GENE_PADRE IS NULL));
INSERT INTO GENERO VALUES (S_GENERO.NEXTVAL,'HISTORICA',NULL);
INSERT INTO GENERO VALUES (S_GENERO.NEXTVAL,'HISTORICA',(SELECT GENE_ID FROM GENERO WHERE GENE_NOMBRE = 'DRAMA' AND GENE_PADRE IS NULL));
INSERT INTO GENERO VALUES (S_GENERO.NEXTVAL,'ROMANCE',(SELECT GENE_ID FROM GENERO WHERE GENE_NOMBRE = 'HISTORICA' AND GENE_PADRE = (SELECT GENE_ID FROM GENERO WHERE GENE_NOMBRE = 'DRAMA' AND GENE_PADRE IS NULL)));
INSERT INTO GENERO VALUES (S_GENERO.NEXTVAL,'POLICIACA',NULL);
INSERT INTO GENERO VALUES (S_GENERO.NEXTVAL,'ROMANCE',(SELECT GENE_ID FROM GENERO WHERE GENE_NOMBRE = 'AVENTURA' AND GENE_PADRE IS NULL));
INSERT INTO GENERO VALUES (S_GENERO.NEXTVAL,'FANTASIA',(SELECT GENE_ID FROM GENERO WHERE GENE_NOMBRE = 'ROMANCE' AND GENE_PADRE = (SELECT GENE_ID FROM GENERO WHERE GENE_NOMBRE = 'AVENTURA' AND GENE_PADRE IS NULL)));
INSERT INTO GENERO VALUES (S_GENERO.NEXTVAL,'MUSICAL',(SELECT GENE_ID FROM GENERO WHERE GENE_NOMBRE = 'FANTASIA' AND GENE_PADRE = (SELECT GENE_ID FROM GENERO WHERE GENE_NOMBRE = 'ROMANCE' AND GENE_PADRE = (SELECT GENE_ID FROM GENERO WHERE GENE_NOMBRE = 'AVENTURA' AND GENE_PADRE IS NULL))));
INSERT INTO GENERO VALUES (S_GENERO.NEXTVAL,'MUSICAL',(SELECT GENE_ID FROM GENERO WHERE GENE_NOMBRE = 'DRAMA' AND GENE_PADRE IS NULL));
INSERT INTO GENERO VALUES (S_GENERO.NEXTVAL,'ROMANCE',(SELECT GENE_ID FROM GENERO WHERE GENE_NOMBRE = 'MUSICAL' AND GENE_PADRE = (SELECT GENE_ID FROM GENERO WHERE GENE_NOMBRE = 'DRAMA' AND GENE_PADRE IS NULL)));
INSERT INTO GENERO VALUES (S_GENERO.NEXTVAL,'GUERRA',(SELECT GENE_ID FROM GENERO WHERE GENE_NOMBRE = 'AVENTURA' AND GENE_PADRE IS NULL));
INSERT INTO GENERO VALUES (S_GENERO.NEXTVAL,'DRAMA',(SELECT GENE_ID FROM GENERO WHERE GENE_NOMBRE = 'GUERRA' AND GENE_PADRE = (SELECT GENE_ID FROM GENERO WHERE GENE_NOMBRE = 'AVENTURA' AND GENE_PADRE IS NULL)));
INSERT INTO GENERO VALUES (S_GENERO.NEXTVAL,'GUERRA',(SELECT GENE_ID FROM GENERO WHERE GENE_NOMBRE = 'DRAMA' AND GENE_PADRE IS NULL));
INSERT INTO GENERO VALUES (S_GENERO.NEXTVAL,'FANTASIA',NULL);
INSERT INTO GENERO VALUES (S_GENERO.NEXTVAL,'INFANTIL',(SELECT GENE_ID FROM GENERO WHERE GENE_NOMBRE = 'FANTASIA' AND GENE_PADRE IS NULL));
INSERT INTO GENERO VALUES (S_GENERO.NEXTVAL,'CRIMEN',NULL);
INSERT INTO GENERO VALUES (S_GENERO.NEXTVAL,'MISTERIO',(SELECT GENE_ID FROM GENERO WHERE GENE_NOMBRE='CRIMEN' AND GENE_PADRE IS NULL));
INSERT INTO GENERO VALUES (S_GENERO.NEXTVAL,'ROMANCE',(SELECT GENE_ID FROM GENERO WHERE GENE_NOMBRE='MISTERIO' AND GENE_PADRE =(SELECT GENE_ID FROM GENERO WHERE GENE_NOMBRE='CRIMEN' AND GENE_PADRE IS NULL)));
INSERT INTO GENERO VALUES (S_GENERO.NEXTVAL,'MISTERIO',(SELECT GENE_ID FROM GENERO WHERE GENE_NOMBRE='DRAMA' AND GENE_PADRE IS NULL));
INSERT INTO GENERO VALUES (S_GENERO.NEXTVAL,'SUSPENSO',(SELECT GENE_ID FROM GENERO WHERE GENE_NOMBRE='MISTERIO' AND GENE_PADRE = (SELECT GENE_ID FROM GENERO WHERE GENE_NOMBRE='DRAMA' AND GENE_PADRE IS NULL)));
INSERT INTO GENERO VALUES (S_GENERO.NEXTVAL,'DRAMA',(SELECT GENE_ID FROM GENERO WHERE GENE_NOMBRE='CRIMEN' AND GENE_PADRE IS NULL));
INSERT INTO GENERO VALUES (S_GENERO.NEXTVAL,'DRAMA',(SELECT GENE_ID FROM GENERO WHERE GENE_NOMBRE = 'AVENTURA' AND GENE_PADRE IS NULL));
INSERT INTO GENERO VALUES (S_GENERO.NEXTVAL,'ROMANCE',(SELECT GENE_ID FROM GENERO WHERE GENE_NOMBRE = 'DRAMA' AND GENE_PADRE = (SELECT GENE_ID FROM GENERO WHERE GENE_NOMBRE = 'AVENTURA' AND GENE_PADRE IS NULL)));
INSERT INTO GENERO VALUES (S_GENERO.NEXTVAL,'SCI-FI',(SELECT GENE_ID FROM GENERO WHERE GENE_NOMBRE = 'ROMANCE' AND GENE_PADRE = (SELECT GENE_ID FROM GENERO WHERE GENE_NOMBRE = 'DRAMA' AND GENE_PADRE = (SELECT GENE_ID FROM GENERO WHERE GENE_NOMBRE = 'AVENTURA' AND GENE_PADRE IS NULL))));
INSERT INTO GENERO VALUES (S_GENERO.NEXTVAL,'GUERRA',(SELECT GENE_ID FROM GENERO WHERE GENE_NOMBRE = 'HISTORICA' AND GENE_PADRE = (SELECT GENE_ID FROM GENERO WHERE GENE_NOMBRE = 'DRAMA' AND GENE_PADRE IS NULL)));
INSERT INTO GENERO VALUES (S_GENERO.NEXTVAL,'GUERRA',(SELECT GENE_ID FROM GENERO WHERE GENE_NOMBRE = 'DRAMA' AND GENE_PADRE = (SELECT GENE_ID FROM GENERO WHERE GENE_NOMBRE = 'DRAMA' AND GENE_PADRE IS NULL)));
INSERT INTO GENERO VALUES (S_GENERO.NEXTVAL,'HISTORICA',(SELECT GENE_ID FROM GENERO WHERE GENE_NOMBRE = 'DRAMA' AND GENE_PADRE = (SELECT GENE_ID FROM GENERO WHERE GENE_NOMBRE = 'AVENTURA' AND GENE_PADRE IS NULL)));
INSERT INTO GENERO VALUES (S_GENERO.NEXTVAL,'ROMANCE',(SELECT GENE_ID FROM GENERO WHERE GENE_NOMBRE = 'DRAMA' AND GENE_PADRE IS NULL));
INSERT INTO GENERO VALUES (S_GENERO.NEXTVAL,'DEPORTE',(SELECT GENE_ID FROM GENERO WHERE GENE_NOMBRE = 'DRAMA' AND GENE_PADRE IS NULL));
INSERT INTO GENERO VALUES (S_GENERO.NEXTVAL,'DRAMA',(SELECT GENE_ID FROM GENERO WHERE GENE_NOMBRE = 'COMEDIA' AND GENE_PADRE IS NULL));
INSERT INTO GENERO VALUES (S_GENERO.NEXTVAL,'CRIMEN',(SELECT GENE_ID FROM GENERO WHERE GENE_NOMBRE = 'DRAMA' AND GENE_PADRE = (SELECT GENE_ID FROM GENERO WHERE GENE_NOMBRE = 'COMEDIA' AND GENE_PADRE IS NULL)));
INSERT INTO GENERO VALUES (S_GENERO.NEXTVAL,'ACCION',(SELECT GENE_ID FROM GENERO WHERE GENE_NOMBRE = 'CRIMEN' AND GENE_PADRE = (SELECT GENE_ID FROM GENERO WHERE GENE_NOMBRE = 'DRAMA' AND GENE_PADRE = (SELECT GENE_ID FROM GENERO WHERE GENE_NOMBRE = 'COMEDIA' AND GENE_PADRE IS NULL))));
INSERT INTO GENERO VALUES (S_GENERO.NEXTVAL,'MISTERIO',NULL);
INSERT INTO GENERO VALUES (S_GENERO.NEXTVAL,'SCI-FI',(SELECT GENE_ID FROM GENERO WHERE GENE_NOMBRE = 'MISTERIO' AND GENE_PADRE IS NULL));
INSERT INTO GENERO VALUES (S_GENERO.NEXTVAL,'THRILLER',(SELECT GENE_ID FROM GENERO WHERE GENE_NOMBRE = 'SCI-FI' AND GENE_PADRE = (SELECT GENE_ID FROM GENERO WHERE GENE_NOMBRE = 'MISTERIO' AND GENE_PADRE IS NULL)));
INSERT INTO GENERO VALUES (S_GENERO.NEXTVAL,'AVENTURA',(SELECT GENE_ID FROM GENERO WHERE GENE_NOMBRE = 'THRILLER' AND GENE_PADRE = (SELECT GENE_ID FROM GENERO WHERE GENE_NOMBRE = 'SCI-FI' AND GENE_PADRE = (SELECT GENE_ID FROM GENERO WHERE GENE_NOMBRE = 'MISTERIO' AND GENE_PADRE IS NULL))));
INSERT INTO GENERO VALUES (S_GENERO.NEXTVAL,'MUSICAL',(SELECT GENE_ID FROM GENERO WHERE GENE_NOMBRE = 'DRAMA' AND GENE_PADRE = (SELECT GENE_ID FROM GENERO WHERE GENE_NOMBRE = 'CRIMEN' AND GENE_PADRE IS NULL)));
INSERT INTO GENERO VALUES (S_GENERO.NEXTVAL,'ACCION',NULL);
INSERT INTO GENERO VALUES (S_GENERO.NEXTVAL,'AVENTURA',(SELECT GENE_ID FROM GENERO WHERE GENE_NOMBRE = 'ACCION' AND GENE_PADRE IS NULL));
INSERT INTO GENERO VALUES (S_GENERO.NEXTVAL,'COMEDIA',(SELECT GENE_ID FROM GENERO WHERE GENE_NOMBRE = 'AVENTURA' AND GENE_PADRE = (SELECT GENE_ID FROM GENERO WHERE GENE_NOMBRE = 'ACCION' AND GENE_PADRE IS NULL)));
INSERT INTO GENERO VALUES (S_GENERO.NEXTVAL,'ROMANCE',(SELECT GENE_ID FROM GENERO WHERE GENE_NOMBRE = 'COMEDIA' AND GENE_PADRE = (SELECT GENE_ID FROM GENERO WHERE GENE_NOMBRE = 'AVENTURA' AND GENE_PADRE = (SELECT GENE_ID FROM GENERO WHERE GENE_NOMBRE = 'ACCION' AND GENE_PADRE IS NULL))));
INSERT INTO GENERO VALUES (S_GENERO.NEXTVAL,'DRAMA',(SELECT GENE_ID FROM GENERO WHERE GENE_NOMBRE = 'MUSICAL' AND GENE_PADRE IS NULL));
INSERT INTO GENERO VALUES (S_GENERO.NEXTVAL,'ROMANCE',(SELECT GENE_ID FROM GENERO WHERE GENE_NOMBRE = 'DRAMA' AND GENE_PADRE = (SELECT GENE_ID FROM GENERO WHERE GENE_NOMBRE = 'MUSICAL' AND GENE_PADRE IS NULL)));
INSERT INTO GENERO VALUES (S_GENERO.NEXTVAL,'FAMILIAR',(SELECT GENE_ID FROM GENERO WHERE GENE_NOMBRE = 'COMEDIA' AND GENE_PADRE IS NULL));
INSERT INTO GENERO VALUES (S_GENERO.NEXTVAL,'ROMANCE',(SELECT GENE_ID FROM GENERO WHERE GENE_NOMBRE = 'FAMILIAR' AND GENE_PADRE = (SELECT GENE_ID FROM GENERO WHERE GENE_NOMBRE = 'COMEDIA' AND GENE_PADRE IS NULL)));
INSERT INTO GENERO VALUES (S_GENERO.NEXTVAL,'MUSICAL',(SELECT GENE_ID FROM GENERO WHERE GENE_NOMBRE = 'ROMANCE' AND GENE_PADRE = (SELECT GENE_ID FROM GENERO WHERE GENE_NOMBRE = 'FAMILIAR' AND GENE_PADRE = (SELECT GENE_ID FROM GENERO WHERE GENE_NOMBRE = 'COMEDIA' AND GENE_PADRE IS NULL))));
INSERT INTO GENERO VALUES (S_GENERO.NEXTVAL,'DOCUMENTAL',NULL);
INSERT INTO GENERO VALUES (S_GENERO.NEXTVAL,'EXTRANJERA',NULL);
INSERT INTO GENERO VALUES (S_GENERO.NEXTVAL,'ROMANCE',(SELECT GENE_ID FROM GENERO WHERE GENE_NOMBRE = 'COMEDIA' AND GENE_PADRE IS NULL));
INSERT INTO GENERO VALUES (S_GENERO.NEXTVAL,'ROMANCE',(SELECT GENE_ID FROM GENERO WHERE GENE_NOMBRE = 'MUSICAL' AND GENE_PADRE = (SELECT GENE_ID FROM GENERO WHERE GENE_NOMBRE = 'DRAMA' AND GENE_PADRE IS NULL)));
INSERT INTO GENERO VALUES (S_GENERO.NEXTVAL,'FANTASIA',(SELECT GENE_ID FROM GENERO WHERE GENE_NOMBRE = 'AVENTURA' AND GENE_PADRE IS NULL));
INSERT INTO GENERO VALUES (S_GENERO.NEXTVAL,'MISTERIO',(SELECT GENE_ID FROM GENERO WHERE GENE_NOMBRE = 'FANTASIA' AND GENE_PADRE = (SELECT GENE_ID FROM GENERO WHERE GENE_NOMBRE = 'AVENTURA' AND GENE_PADRE IS NULL)));
INSERT INTO GENERO VALUES (S_GENERO.NEXTVAL,'CORTOMETRAJE',NULL);
INSERT INTO GENERO VALUES (S_GENERO.NEXTVAL,'COMEDIA',(SELECT GENE_ID FROM GENERO WHERE GENE_NOMBRE = 'ACCION' AND GENE_PADRE IS NULL));
INSERT INTO GENERO VALUES (S_GENERO.NEXTVAL,'CRIMEN',(SELECT GENE_ID FROM GENERO WHERE GENE_NOMBRE = 'COMEDIA' AND GENE_PADRE = (SELECT GENE_ID FROM GENERO WHERE GENE_NOMBRE = 'ACCION' AND GENE_PADRE IS NULL)));
INSERT INTO GENERO VALUES (S_GENERO.NEXTVAL,'ROMANCE',NULL);
INSERT INTO GENERO VALUES (S_GENERO.NEXTVAL,'COMEDIA',(SELECT GENE_ID FROM GENERO WHERE GENE_NOMBRE = 'ROMANCE' AND GENE_PADRE IS NULL));
INSERT INTO GENERO VALUES (S_GENERO.NEXTVAL,'FANTASIA',(SELECT GENE_ID FROM GENERO WHERE GENE_NOMBRE = 'COMEDIA' AND GENE_PADRE = (SELECT GENE_ID FROM GENERO WHERE GENE_NOMBRE = 'ROMANCE' AND GENE_PADRE IS NULL)));
INSERT INTO GENERO VALUES (S_GENERO.NEXTVAL,'THRILLER',(SELECT GENE_ID FROM GENERO WHERE GENE_NOMBRE = 'ROMANCE' AND GENE_PADRE = (SELECT GENE_ID FROM GENERO WHERE GENE_NOMBRE = 'DRAMA' AND GENE_PADRE IS NULL)));
INSERT INTO GENERO VALUES (S_GENERO.NEXTVAL,'ROMANCE',(SELECT GENE_ID FROM GENERO WHERE GENE_NOMBRE = 'DRAMA' AND GENE_PADRE = (SELECT GENE_ID FROM GENERO WHERE GENE_NOMBRE = 'COMEDIA' AND GENE_PADRE IS NULL)));
INSERT INTO GENERO VALUES (S_GENERO.NEXTVAL,'DRAMA',(SELECT GENE_ID FROM GENERO WHERE GENE_NOMBRE = 'AVENTURA' AND GENE_PADRE = (SELECT GENE_ID FROM GENERO WHERE GENE_NOMBRE = 'ACCION' AND GENE_PADRE IS NULL)));
INSERT INTO GENERO VALUES (S_GENERO.NEXTVAL,'THRILLER',(SELECT GENE_ID FROM GENERO WHERE GENE_NOMBRE = 'DRAMA' AND GENE_PADRE = (SELECT GENE_ID FROM GENERO WHERE GENE_NOMBRE = 'AVENTURA' AND GENE_PADRE = (SELECT GENE_ID FROM GENERO WHERE GENE_NOMBRE = 'ACCION' AND GENE_PADRE IS NULL))));
INSERT INTO GENERO VALUES (S_GENERO.NEXTVAL,'BIOGRAFIA',(SELECT GENE_ID FROM GENERO WHERE GENE_NOMBRE = 'AVENTURA' AND GENE_PADRE IS NULL));
INSERT INTO GENERO VALUES (S_GENERO.NEXTVAL,'DRAMA',(SELECT GENE_ID FROM GENERO WHERE GENE_NOMBRE = 'BIOGRAFIA' AND GENE_PADRE = (SELECT GENE_ID FROM GENERO WHERE GENE_NOMBRE = 'AVENTURA' AND GENE_PADRE IS NULL)));
INSERT INTO GENERO VALUES (S_GENERO.NEXTVAL,'ROMANCE',(SELECT GENE_ID FROM GENERO WHERE GENE_NOMBRE = 'DRAMA' AND GENE_PADRE = (SELECT GENE_ID FROM GENERO WHERE GENE_NOMBRE = 'BIOGRAFIA' AND GENE_PADRE = (SELECT GENE_ID FROM GENERO WHERE GENE_NOMBRE = 'AVENTURA' AND GENE_PADRE IS NULL))));
INSERT INTO GENERO VALUES (S_GENERO.NEXTVAL,'THRILLER',(SELECT GENE_ID FROM GENERO WHERE GENE_NOMBRE = 'MISTERIO' AND GENE_PADRE = (SELECT GENE_ID FROM GENERO WHERE GENE_NOMBRE = 'DRAMA' AND GENE_PADRE IS NULL)));
INSERT INTO GENERO VALUES (S_GENERO.NEXTVAL,'COMEDIA',(SELECT GENE_ID FROM GENERO WHERE GENE_NOMBRE = 'AVENTURA' AND GENE_PADRE IS NULL));
INSERT INTO GENERO VALUES (S_GENERO.NEXTVAL,'ROMANCE',(SELECT GENE_ID FROM GENERO WHERE GENE_NOMBRE = 'COMEDIA' AND GENE_PADRE = (SELECT GENE_ID FROM GENERO WHERE GENE_NOMBRE = 'AVENTURA' AND GENE_PADRE IS NULL)));
INSERT INTO GENERO VALUES (S_GENERO.NEXTVAL,'FANTASIA',(SELECT GENE_ID FROM GENERO WHERE GENE_NOMBRE = 'DRAMA' AND GENE_PADRE IS NULL));
INSERT INTO GENERO VALUES (S_GENERO.NEXTVAL,'SCI-FI',(SELECT GENE_ID FROM GENERO WHERE GENE_NOMBRE = 'FANTASIA' AND GENE_PADRE = (SELECT GENE_ID FROM GENERO WHERE GENE_NOMBRE = 'DRAMA' AND GENE_PADRE IS NULL)));
INSERT INTO GENERO VALUES (S_GENERO.NEXTVAL,'DRAMA',(SELECT GENE_ID FROM GENERO WHERE GENE_NOMBRE = 'ACCION' AND GENE_PADRE IS NULL));
INSERT INTO GENERO VALUES (S_GENERO.NEXTVAL,'GUERRA',(SELECT GENE_ID FROM GENERO WHERE GENE_NOMBRE = 'DRAMA' AND GENE_PADRE = (SELECT GENE_ID FROM GENERO WHERE GENE_NOMBRE = 'ACCION' AND GENE_PADRE IS NULL)));
INSERT INTO GENERO VALUES (S_GENERO.NEXTVAL,'FAMILIA',(SELECT GENE_ID FROM GENERO WHERE GENE_NOMBRE = 'AVENTURA' AND GENE_PADRE IS NULL));
INSERT INTO GENERO VALUES (S_GENERO.NEXTVAL,'HISTORIA',(SELECT GENE_ID FROM GENERO WHERE GENE_NOMBRE = 'DOCUMENTAL' AND GENE_PADRE IS NULL));
INSERT INTO GENERO VALUES (S_GENERO.NEXTVAL,'GUERRA',(SELECT GENE_ID FROM GENERO WHERE GENE_NOMBRE = 'DOCUMENTAL' AND GENE_PADRE IS NULL));
INSERT INTO GENERO VALUES (S_GENERO.NEXTVAL,'COMEDIA',(SELECT GENE_ID FROM GENERO WHERE GENE_NOMBRE = 'DRAMA' AND GENE_PADRE = (SELECT GENE_ID FROM GENERO WHERE GENE_NOMBRE = 'MUSICAL' AND GENE_PADRE IS NULL)));
INSERT INTO GENERO VALUES (S_GENERO.NEXTVAL,'THRILLER',(SELECT GENE_ID FROM GENERO WHERE GENE_NOMBRE = 'HISTORICA' AND GENE_PADRE = (SELECT GENE_ID FROM GENERO WHERE GENE_NOMBRE = 'DRAMA' AND GENE_PADRE IS NULL)));
INSERT INTO GENERO VALUES (S_GENERO.NEXTVAL,'GUERRA',(SELECT GENE_ID FROM GENERO WHERE GENE_NOMBRE = 'THRILLER' AND GENE_PADRE = (SELECT GENE_ID FROM GENERO WHERE GENE_NOMBRE = 'HISTORICA' AND GENE_PADRE = (SELECT GENE_ID FROM GENERO WHERE GENE_NOMBRE = 'DRAMA' AND GENE_PADRE IS NULL))));
INSERT INTO GENERO VALUES (S_GENERO.NEXTVAL,'ARTE',NULL);
INSERT INTO GENERO VALUES (S_GENERO.NEXTVAL,'DRAMA',(SELECT GENE_ID FROM GENERO WHERE GENE_NOMBRE = 'ARTE' AND GENE_PADRE IS NULL));
INSERT INTO GENERO VALUES (S_GENERO.NEXTVAL,'GUERRA',(SELECT GENE_ID FROM GENERO WHERE GENE_NOMBRE = 'DRAMA' AND GENE_PADRE = (SELECT GENE_ID FROM GENERO WHERE GENE_NOMBRE = 'ARTE' AND GENE_PADRE IS NULL)));
INSERT INTO GENERO VALUES (S_GENERO.NEXTVAL,'BIOGRAFIA',(SELECT GENE_ID FROM GENERO WHERE GENE_NOMBRE = 'HISTORICA' AND GENE_PADRE = (SELECT GENE_ID FROM GENERO WHERE GENE_NOMBRE = 'DRAMA' AND GENE_PADRE IS NULL)));
INSERT INTO GENERO VALUES (S_GENERO.NEXTVAL,'WESTERN',(SELECT GENE_ID FROM GENERO WHERE GENE_NOMBRE = 'ACCION' AND GENE_PADRE IS NULL));
INSERT INTO GENERO VALUES (S_GENERO.NEXTVAL,'SCI-FI',(SELECT GENE_ID FROM GENERO WHERE GENE_NOMBRE = 'AVENTURA' AND GENE_PADRE IS NULL));
INSERT INTO GENERO VALUES (S_GENERO.NEXTVAL,'ANIMADO',NULL);
INSERT INTO GENERO VALUES (S_GENERO.NEXTVAL,'DRAMA',(SELECT GENE_ID FROM GENERO WHERE GENE_NOMBRE = 'COMEDIA' AND GENE_PADRE = (SELECT GENE_ID FROM GENERO WHERE GENE_NOMBRE = 'AVENTURA' AND GENE_PADRE IS NULL)));
INSERT INTO GENERO VALUES (S_GENERO.NEXTVAL,'THRILLER',(SELECT GENE_ID FROM GENERO WHERE GENE_NOMBRE = 'AVENTURA' AND GENE_PADRE = (SELECT GENE_ID FROM GENERO WHERE GENE_NOMBRE = 'ACCION' AND GENE_PADRE IS NULL)));
INSERT INTO GENERO VALUES (S_GENERO.NEXTVAL,'FANTASIA',(SELECT GENE_ID FROM GENERO WHERE GENE_NOMBRE = 'DRAMA' AND GENE_PADRE = (SELECT GENE_ID FROM GENERO WHERE GENE_NOMBRE = 'COMEDIA' AND GENE_PADRE IS NULL)));

rem / INSERTS PELICULAS /

INSERT INTO "PELICULA" VALUES (1, 'A STREET CAR NAMED DESIRE', NULL, NULL, 'Blanche, una mujer madura y anclada en el pasado, visita a su hermana Stella y a su marido Stanley, un joven rústico y violento, que vive en Nueva Orleans y que tiene ascendencia polaca. Blanche decide quedarse durante un período indefinido viviendo con su hermana. Es en este momento cuando ella (Blanche) le cuenta sobre la pérdida de una antigua propiedad de la familia llamada Belle Reeve. Esto levanta sospechas en el marido de Stella quien decide investigar más acerca de Blanche; quien averigua sobre el pasado escabroso de Blanche. Esto creará conflictos en la joven pareja, especialmente entre Blanche y Stanley (marido de Stella) y ella poco a poco dejará mostrar su estado mental no saludable.', 122, TO_DATE('19510825000000', 'YYYYMMDDHH24MISS'), NULL, NULL, 'INGLES', 'GP', 1, 1, NULL);
INSERT INTO "PELICULA" VALUES (2, 'A PLACE IN THE SUN', NULL, NULL, 'George Eastman es un joven sin dinero decidido a forjarse un porvenir en la alta sociedad y robar el corazón a la joven Angela Vickers. Alice Tripp es la típica chica de una fábrica que posee un oscuro secreto que amenaza las perspectivas profesionales y románticas de Eastman. Consumido por el temor y el deseo, éste se ve empujado a una locura que tirará por tierra su futuro.', 122, TO_DATE('19510814000000', 'YYYYMMDDHH24MISS'), NULL, NULL, 'INGLES', 'A', 1, 1, NULL);
INSERT INTO "PELICULA" VALUES (3, 'AN AMERICAN IN PARIS', NULL, NULL, 'Un artista americano que vive en París reparte su corazón entre una mujer adinerada y una pobre huérfana.', 115, TO_DATE('19511004000000', 'YYYYMMDDHH24MISS'), NULL, NULL, 'INGLES', 'A', 1, 2, NULL);
INSERT INTO "PELICULA" VALUES (4, 'THE AFRICAN QUEEN', NULL, NULL, 'September 1914, news reaches the colony German Eastern Africa that its motherland is at war, so Reverend Samuel Sayer became a hostile foreigner; German imperial troops burn down his mission, driving him mad- shortly after his well-educated, snooty sister Rose Sayer buries him and leaves by the only available transport, the crummy river steamboat ''African Queen'' of grumpy boorish compatriot Charlie Allnut. As if a long difficult journey without any comfort weren''t bad enough for such odd companions, she is determined to find a way to do their bit for the British war effort (and revenge her brother) and aims high as God is obviously on their side: construct their own equipment, a torpedo and the converted steamboat, to take out a huge German warship, the Louisa, which is hard to find on the giant lake and first of all to reach, in fact as daunting an expedition as nobody attempted since the late adventurous explorer John Speakes, but she presses till Charlie accepts to steam up the Ulana, about to brave a German fort, raging rapids, very bloodthirsty parasites and the endlessly branching stream which seems to go nowhere but impenetrable swamps... Despite fierce rows and moral antagonism between a bossy devout abstentionist and a free-spirited libertine drunk loner, the two bachelors grow closer to each-other as their quest drags on.', 105, TO_DATE('19510220000000', 'YYYYMMDDHH24MISS'), NULL, NULL, 'INGLES', 'A', 1, 3, NULL);
INSERT INTO "PELICULA" VALUES (5, 'THE GREAT CARUSO', NULL, NULL, 'Loosely traces the life of tenor Enrico Caruso (1873-1921). He loves Musetta, in his home town of Naples, and then Dorothy, the daughter of one of the Metropolitan Opera''s patrons. Caruso is unacceptable to both women''s fathers: to one, because he sings; to Dorothy''s, because he is a peasant. To New York patricians, Caruso is short, barrel chested, loud, emotional, unrefined. Their appreciation comes slowly. The film depicts Caruso''s lament that "the man does not have the voice, the voice has the man": he cannot be places he wants to be, because he must be elsewhere singing, including the day his mother dies. Throughout, Mario Lanza and stars from the Met sing.', 109, TO_DATE('19510416000000', 'YYYYMMDDHH24MISS'), NULL, NULL, 'INGLES', 'A', 1, 6, NULL);
INSERT INTO "PELICULA" VALUES (6, 'HERE COMES THE GROOM', NULL, NULL, 'Newspaper reporter Pete (Bing Crosby) works in aParis orphanage. His charming way with children and music enables him to find homes for even the most troubled kids. One afternoon, Mr. and Mrs. Godfrey (Alan Reed andMinna Gombell), an American couple, come to the orphanage to adopt Bobby, a boy they saw in one of the ads Pete ran in his newspaper. Bobby misbehaves, but when Pete discovers that Mr. Godfrey plays for the Philadelphia Symphony Orchestra, he quickly produces a young blind operawunderkind, Theresa (Anna Maria Alberghetti), who sings her way into the Godfreys'' hearts.', 113, TO_DATE('19510920000000', 'YYYYMMDDHH24MISS'), NULL, NULL, 'INGLES', 'A', 1, 9, NULL);
INSERT INTO "PELICULA" VALUES (7, 'WHEN WORLDS COLLIDE', NULL, NULL, 'David Randall is a carefree ladies man and skilled pilot who finds he has been let in on the greatest and most terrible secret in the world when he is paid to deliver some mysterious pictures from one eminent astronomer to another. The recipient, Dr. Hendron, confirms the awful findings of the sender: the planet Zyra will collide with Earth and wipe out all of humanity. Despite widespread disbelief, two philanthropists give Dr. Hendron some of the money he needs to build a rocket ship that will, at least theoretically, take them to Zyra, which may or may not be habitable for humans. The rest of the money comes from Sydney Stanton, a wheelchair-bound old man, who insists he come along, despite the severe limitations on the number of passengers and amount of cargo. Meanwhile, as doomsday approaches, Randall is surprised to find himself in a love triangle with Dr. Hendron''s daughter and her fiancé. Humanity is in peril, and only a modern-day Noah''s ark, and the continued need of a man for a woman, can save it.', 83, TO_DATE('19510801000000', 'YYYYMMDDHH24MISS'), NULL, NULL, 'INGLES', 'G', 1, 10, NULL);
INSERT INTO "PELICULA" VALUES (8, 'RASHOMON', NULL, NULL, 'In 12th century Japan, a samurai and his wife are attacked by the notorious bandit Tajomaru, and the samurai ends up dead. Tajomaru is captured shortly afterward and is put on trial, but his story and the wife''s are so completely different that a psychic is brought in to allow the murdered man to give his own testimony. He tells yet another completely different story. Finally, a woodcutter who found the body reveals that he saw the whole thing, and his version is again completely different from the others.', 88, TO_DATE('19511226000000', 'YYYYMMDDHH24MISS'), NULL, NULL, 'JAPONES', 'UR', 5, 1, NULL);
INSERT INTO "PELICULA" VALUES (9, 'SEVEN DAYS TO NOON', NULL, NULL, 'An English scientist runs away from a research center with an atomic bomb. In a letter sent to the British Prime Minister he threatens to blow up the center of London if the Government don''t announce the end of any research in this field within a week. Special agents from Scotland Yard try to stop him, with help from the scientist''s assistant future son-in-law to find and stop the mad man.', 94, TO_DATE('19511010000000', 'YYYYMMDDHH24MISS'), NULL, NULL, 'INGLES', 'A', 6, 11, NULL);
INSERT INTO "PELICULA" VALUES (10, 'QUO VADIS', NULL, NULL, 'Returning to Rome after 3 years in the field, General Marcus Vinicius meets Lygia and falls in love with her. She is a Christian and doesn''t want to have anything to do with a warrior. Though she grew up Roman, the adopted daughter of a retired general, Lygia is technically a hostage of Rome. Marcus gets Emperor Nero to give her to him for services rendered. Lygia resents this, but somehow falls in love with Marcus anyway. Meanwhile Nero''s atrocities get more outrageous. When he burns Rome and blames the Christians, Marcus goes off to save Lygia and her family. Nero captures them and all the Christians, and throws them to the lions.', 171, TO_DATE('19511108000000', 'YYYYMMDDHH24MISS'), NULL, NULL, 'INGLES', 'A', 1, 12, NULL);
INSERT INTO "PELICULA" VALUES (11, 'DAVID AND BATHSHEBA', NULL, NULL, 'Though David has all the wealth, power, wives & children inherent for the King of Israel he does not have what he craves most: the true love of a woman who loves him as a man instead of as King. He is attracted to Bathsheba, the wife of one of his soldiers who is more devoted to army duty than to his wife. David & Bathsheba succumb to their feelings. Their affair, her resulting pregnancy, & David''s resolve to have her husband killed so Bathsheba will be free to marry, bring the wrath of God upon the kingdom. David must rediscover his faith in God in order to save Bathsheba from death by stoning, his kingdom from drought & famine, & himself from his many sins.', 123, TO_DATE('19510810000000', 'YYYYMMDDHH24MISS'), NULL, NULL, 'INGLES', 'A', 1, 14, NULL);
INSERT INTO "PELICULA" VALUES (14, 'THE TAILS OF HOFFMANN', NULL, NULL, 'Hoffmann is a lovelorn young man in Nuremberg who is watching his latest love, Stella, dance in the ballet. In the interval he goes to the tavern where he tells his friends the tales of the three major loves of his life. Each story forms a separate act of this magnificently staged opera. It is NOT just a film of a staged production but a truly filmic version of the Offenbach opera.', 128, TO_DATE('19510404000000', 'YYYYMMDDHH24MISS'), NULL, NULL, 'INGLES', 'A', 6, 18, NULL);
INSERT INTO "PELICULA" VALUES (12, 'DEATH OF A SASALESMAN', NULL, NULL, 'Willy Loman has led a life consisting of sixty years of failure. Loman''s wife supports him, but he soon begins to lose his grip on reality and slips between the past and the present, frantically trying to find where he went wrong.', 115, TO_DATE('19510830000000', 'YYYYMMDDHH24MISS'), NULL, NULL, 'INGLES', 'A', 1, 1, NULL);
INSERT INTO "PELICULA" VALUES (13, 'DETECTIVE STORY', NULL, NULL, 'Jim McLeod is a hard-nosed and cynical detective. He believes in a strict interpretation of the law and doesn''t believe in turning the other cheek. The current object of his zealousness is Karl Schneider, an abortionist responsible for the death of several young women. Schneider''s lawyer tells the precinct lieutenant that McLeod has his own personal reasons for going after his client. It turns out that his wife was a patient before they met, although Jim knew nothing of it. His world suddenly turned upside down, McLeod is too late in re-evaluating his priorities.', 103, TO_DATE('19511106000000', 'YYYYMMDDHH24MISS'), NULL, NULL, 'INGLES ', 'A', 1, 15, NULL);
INSERT INTO "PELICULA" VALUES (15, 'DESCISION BEFORE DAWN', NULL, NULL, 'WWII is entering its last phase: Germany is in ruins, but does not yield. The US army lacks crucial knowledge about the German units operating on the opposite side of the Rhine, and decides to send two German prisoners to gather information. The scheme is risky: the Gestapo retains a terribly efficient network to identify and capture spies and deserters. Moreover, it is not clear that "Tiger", who does not mind any dirty work as long as the price is right, and war-weary "Happy", who might be easily betrayed by his feelings, are dependable agents. After Tiger and another American agent are successfully infiltrated, Happy is parachuted in Bavaria. His duty: find out the whereabouts of a powerful German armored unit moving towards the western front.', 119, TO_DATE('19510607000000', 'YYYYMMDDHH24MISS'), NULL, NULL, 'INGLES', 'A', 1, 1, NULL);
INSERT INTO "PELICULA" VALUES (16, 'THE BLUE VEIL', NULL, NULL, 'Louise Mason is a young widow who fills her empty life with the task of becoming a children''s nurse. As the years pass, and the widow tries to find her own place in life, her young charges, the children of various employers, grow and soon find themselves ready to face the world. When it seems that she will be alone, the nurse finds that her ''children'' have ideas of their own in regards to helping their beloved mentor.', 113, TO_DATE('19511026000000', 'YYYYMMDDHH24MISS'), NULL, NULL, 'INGLES', 'A', 1, 1, NULL);
INSERT INTO "PELICULA" VALUES (17, 'BRIGHT VICTORY', NULL, NULL, 'In North Africa during World War II, Sergeant Larry Nevins is blinded by a German sniper''s bullet. Rehabilitation at the military hospital presents many challenges, but accepting his disability also proves to be difficult for others.', 96, TO_DATE('19510309000000', 'YYYYMMDDHH24MISS'), NULL, NULL, 'INGLES', 'A', 1, 1, NULL);
INSERT INTO "PELICULA" VALUES (18, 'ON THE RIVIERA', NULL, NULL, 'Jack Martin (Danny Kaye), an American entertainer working cabarets on the French Riviera, does an impersonation of philandering industrialist Henri Duran (Kaye, again) so convincingly that even Duran''s beautiful wife (Gene Tierney) is fooled by it. When Duran''s business interests compel him to be in London when he should be hosting a large soiree at his home, Martin is persuaded to impersonate Duran at the party. But matters threaten to get out of hand when Martin (as Duran) is confronted by several of the philanderer''s women, and by Duran''s ruthless business rival, M. Periton (Jean Murat).', 90, TO_DATE('19510420000000', 'YYYYMMDDHH24MISS'), NULL, NULL, 'INGLES', 'A', 1, 8, NULL);
INSERT INTO "PELICULA" VALUES (19, 'THE WELL', NULL, NULL, 'In a racially mixed American town, a 5-year-old black girl falls unnoticed into a hidden, forgotten well on her way to school. Having nothing better to go on, the police follow up a report that the child was seen with a white stranger, and rumors run wild. Before hapless, innocent Claude Packard is even found, popular hysteria has him tried and convicted. But Packard''s troubles pale by comparison as ever more inflated rumors uncap the well of racial tensions and mob violence. And young Carolyn Crawford, forgotten by most, is still missing.', 86, TO_DATE('19510124000000', 'YYYYMMDDHH24MISS'), NULL, NULL, 'INGLES', 'A', 1, 1, NULL);
INSERT INTO "PELICULA" VALUES (20, 'LA RONDE', NULL, NULL, 'An all-knowing interlocutor guides us through a series of affairs in Vienna, 1900. A soldier meets an eager young lady of the evening. Later he has an affair with a young lady, who becomes a maid and does similarly with the young man of the house. The young man seduces a married woman. On and on, spinning on the gay carousel of life.', 95, TO_DATE('19510316000000', 'YYYYMMDDHH24MISS'), NULL, NULL, 'FRANCES', 'PG', 7, 1, NULL);
INSERT INTO "PELICULA" VALUES (21, 'SHOW BOAT', NULL, NULL, 'When Julie la Verne and her husband Steve Baker are forced to leave the showboat Cotton Blossom (their marriage is illegal because of Julie''s mixed blood),their places are taken by Magnolia Hawks, the Captain''s daughter, and Gaylord Ravenal, a gambler. Magnolia and Ravenal fall in love, marry, leave the boat and move to Chicago, where they live off Ravenal''s earnings from gambling. After they go broke Gay feels guilty and leaves Magnolia, not knowing she is pregnant.', 107, TO_DATE('19510924000000', 'YYYYMMDDHH24MISS'), NULL, NULL, 'INGLES', 'A', 1, 20, NULL);
INSERT INTO "PELICULA" VALUES (22, 'THE FROG MEN', NULL, NULL, 'World War II drama in which Richard Widmark, as Lt. Cmdr. John Lawrence, replaces the popular commanding officer of a group of underwater demolition divers. a crew of fiercely independent studs who hang their proverbial hats in Davy Jones'' locker. The martinet Lawrence tightens the discipline of the unit, making him mucho unpopular with the macho frogmen. Finally, Lawrence proves himself as more than just a stuffed white shirt, showing he has the cojones to keep up with their peculiar brand of the jones, becoming one of the team by fearlessly defusing a live torpedo at the risk of his own life.', 96, TO_DATE('19510629000000', 'YYYYMMDDHH24MISS'), NULL, NULL, 'INGLES', 'A', 1, 22, NULL);
INSERT INTO "PELICULA" VALUES (23, 'THE MATING SEASON', NULL, NULL, 'Ellen McNulty sells her New Jersey hamburger stand and heads west to pay a surprise visit to her son and his new bride. When Ellen arrives, her daughter-in-law mistakes her for the maid she has hired for a big party her husband is throwing to impress his boss. Rather than cause any embarrassment, Ellen goes along with the charade, which leads to many complications.', 101, TO_DATE('19510531000000', 'YYYYMMDDHH24MISS'), NULL, NULL, 'INGLES', 'A', 1, 7, NULL);
INSERT INTO "PELICULA" VALUES (24, 'TERESA', NULL, NULL, 'Teresa Wilms Montt una arístocrática joven de la clase alta chilena de principio de siglo se ve obligada a vivir una matrimonio desdichado hasta que la obligan a recluirse en un convento, desde donde con la ayuda del poeta Vicente Huidobro logrará fugarse a Buenos Aires.', 85, TO_DATE('19511228000000', 'YYYYMMDDHH24MISS'), NULL, NULL, 'CASTELLANO', 'A', 8, 1, NULL);
INSERT INTO "PELICULA" VALUES (25, 'GO FOR BROKE!', NULL, NULL, 'A tribute to the U.S. 442nd Regimental Combat Team, formed in 1943 by Presidential permission with Japanese-American volunteers. We follow the training of a platoon under the rueful command of Lt. Mike Grayson who shares common prejudices of the time. The 442nd serve in Italy, then France, distinguishing themselves in skirmishes and battles; gradually and naturally, Grayson''s prejudices evaporate with dawning realization that his men are better soldiers than he is. Not preachy.', 92, TO_DATE('19510314000000', 'YYYYMMDDHH24MISS'), NULL, NULL, 'INGLES', 'A', 1, 23, NULL);
INSERT INTO "PELICULA" VALUES (26, 'ALICE IN WONDERLAND', NULL, NULL, 'On a golden afternoon, young Alice follows a White Rabbit, who disappears down a nearby rabbit hole. Quickly following him, she tumbles into the burrow - and enters the merry, topsy-turvy world of Wonderland! Memorable songs and whimsical escapades highlight Alice''s journey, which culminates in a madcap encounter with the Queen of Hearts - and her army of playing cards!', 75, TO_DATE('19510728000000', 'YYYYMMDDHH24MISS'), NULL, NULL, 'INGLES', 'A', 1, 24, NULL);
INSERT INTO "PELICULA" VALUES (27, 'GOLDEN GIRL', NULL, NULL, 'Against the background of the Civil War, sixteen-year-old song-and-dance artiste Lotta Crabtree works her way across America, becoming ever more popular.', 108, TO_DATE('19511101000000', 'YYYYMMDDHH24MISS'), NULL, NULL, 'INGLES', 'A', 1, 2, NULL);
INSERT INTO "PELICULA" VALUES (28, 'ROYAL WEDDING', NULL, NULL, 'Stage stars Tom and Ellen Bowen embark to open their show in England. Innocent-seeming Ellen is a female Don Juan and doesn''t take dancing as seriously as brother Tom; on shipboard she meets her match, Lord John Brindale. Arrived in London, confirmed bachelor Tom auditions and is taken with cool dancer Anne Ashmond. Will romance break up the act?', 93, TO_DATE('19510308000000', 'YYYYMMDDHH24MISS'), NULL, NULL, 'INGLES', 'PG', 1, 9, NULL);
INSERT INTO "PELICULA" VALUES (29, 'RICH YOUNG AND PRETTY', NULL, NULL, 'Rich, Young and Pretty succinctly describes Jane Powell, the heroine of this frothy MGM musical. Vacationing in Paris with her father, Jim Stauton Rogers (Wendell Corey) -- a cattle baron-turned-politician, Elizabeth Rogers (Powell) falls in love with handsome Andre Milan (Vic Damone, in his film debut). She also learns to her surprise that her Gallic mother, Marie (Danielle Darrieux), is not dead as she''s been led to believe, but very much alive and very much involved with suave South American Paul Sarnac (Fernando Lamas). The plot is merely there to provide breathing space for the film''s ten -- count ''em, ten -- musical numbers. If Rich, Young and Pretty resembles a Deanna Durbin picture at times, it may because it was produced by Durbin''s discoverer, Joseph Pasternak.', 95, TO_DATE('19510724000000', 'YYYYMMDDHH24MISS'), NULL, NULL, 'INGLES', 'A', 1, 2, NULL);
INSERT INTO "PELICULA" VALUES (30, 'STRANGERS ON A TRAIN', NULL, NULL, 'Psychotic mother''s boy Bruno Anthony meets famous tennis professional Guy Haines on a train. Guy wants to move into a career in politics and has been dating a senator''s daughter (Ann Morton) while awaiting a divorce from his wife. Bruno wants to kill his father but knows he will be caught because he has a motive. Bruno dreams up a crazy scheme in which he and Guy exchange murders. Guy takes this as a joke, but Bruno is serious and takes things into his own hands.', 101, TO_DATE('19510630000000', 'YYYYMMDDHH24MISS'), NULL, NULL, 'INGLES', 'A', 1, 28, NULL);
INSERT INTO "PELICULA" VALUES (31, 'THE HOUSE ON TELEGRAPH HILL', NULL, NULL, 'Victoria has survived Nazi concentration by assuming the identity of one who died there. She arrives in San Francisco to see her "son" just as the boy''s great-aunt dies leaving a lot of money to be inherited. Victoria falls in love with the boy''s trustee Alan Spender, and they move into the mansion on Telegraph Hill. She then learns that Alan and his lover, the boy''s governess Margaret, murdered an aunt and are planning the same for her.', 93, TO_DATE('19510513000000', 'YYYYMMDDHH24MISS'), NULL, NULL, 'INGLES', 'A', 1, 30, NULL);
INSERT INTO "PELICULA" VALUES (32, 'TOO YOUNG TO KISS', NULL, NULL, 'Eric Wainwright (Van Johnson), a busy impresario, is besieged by hordes of wannabe concert stars, eager for their big break. One of them is Cynthia Potter (June Allyson), a talented pianist... but she can''t get in to see him. When she learns that Wainwright is auditioning young musicians for a children''s concert tour, Cynthia dons braces and bobby sox and passes herself off as a child prodigy.', 91, TO_DATE('19511122000000', 'YYYYMMDDHH24MISS'), NULL, NULL, 'INGLES', 'A', 1, 7, NULL);
INSERT INTO "PELICULA" VALUES (33, 'KNOCK ON ANY DOOR', NULL, NULL, 'Andrew Morton is an attorney who made it out of the slums. Nick Romano is his client, a young man with a long string of crimes behind him. After he lost his paycheck gambling, hoping to buy his wife some jewelry, she announced she was pregnant, Later he finds her dead from suicide. When he turns again to robbery he''s caught by a cop and Nick pumps all his bullets into him in frustration. Morton''s appeal to the court emphasizes the evils of the slums.', 100, TO_DATE('19510222000000', 'YYYYMMDDHH24MISS'), NULL, NULL, 'INGLES', 'A', 1, 31, NULL);

rem / INSERTS COMPANIAS /

INSERT INTO "DISTRIBUCION_COMP" VALUES (1, 'Charles K. Feldman Group', NULL);
INSERT INTO "DISTRIBUCION_COMP" VALUES (2, 'Paramount Pictures', 'Paramount Pictures Corporation es una compañía estadounidense productora y distribuidora de cine, con sede en Hollywood (California). Está controlada por Viacom. Antes controlada por Gulf Western Company. Fue fundada el 18 de diciembre de 1908 pero controlada por primera vez en 1910.');
INSERT INTO "DISTRIBUCION_COMP" VALUES (3, 'Metro-Goldwyn-Mayer', 'Metro-Goldwyn-Mayer Inc. (o simplemente MGM) es una gran compañía, involucrada principalmente en la producción y distribución de películas de cine y programas de televisión. Sus principales subsidiarios fueron MGM Studios Inc., United Artists Corporation y Orion Pictures Corporation (adquirida en 1997). En una importante operación mercantil, la empresa fue vendida a un grupo de compañías encabezadas por Sony Pictures Entertainment que es también propietaria de Columbia Pictures.');
INSERT INTO "DISTRIBUCION_COMP" VALUES (4, 'RKO Radio Pictures', 'La RKO es una compañía cinematográfica estadounidense, considerado uno de los "cinco" grandes estudios de la época dorada de Hollywood.');
INSERT INTO "DISTRIBUCION_COMP" VALUES (5, 'British Lion Film Corporation', 'British Lion Films Corporation is a film production and distribution company active under several forms since 1919. Until 1976 they were also film distributors as British Lion Films Ltd, with a distributor filmography of 232 films. As a production company they are still active and have produced over 170 films.');
INSERT INTO "DISTRIBUCION_COMP" VALUES (6, 'Twentieth Century-Fox', 'Twentieth (20th) Century Fox es el nombre abreviado de la Corporación Fílmica Twentieth Century Fox, es uno de los principales estudios de cine, situado en el área de Century City en Los Ángeles (California), USA, justo al oeste de Beverly Hills. Este estudio es una subsidiaria de News Corporation, el conglomerado mediático controlado por Rupert Murdoch.');
INSERT INTO "DISTRIBUCION_COMP" VALUES (7, 'Columbia Pictures', 'El logotipo del estudio de Columbia Pictures representa la personificación del sexo femenino de América. Fue diseñado en el año 1924 por primera vez y surgió con un nombre diferente aunque finalmente optaron por Columbia. En 1962, en la autobiografía de Bette Davis afirmó que Claudia Bell era la modelo mientras que en 1987 Magazine nombró como modelo a la actriz de Columbia Amelia Batchier. En 2001, el Chicago Sun-Times nombró a una mujer local que trabajó como modelo de extras en Columbia llamada Bartholomew. Sólo tres eran correctos.');
INSERT INTO "DISTRIBUCION_COMP" VALUES (8, 'Lopert Pictures', NULL);
INSERT INTO "DISTRIBUCION_COMP" VALUES (9, 'Universal Pictures', 'Universal Studios, también conocida como Estudios Universal o simplemente Universal, es una compañía estadounidense dedicada a la producción y distribución cinematográfica. Es uno de los seis principales estudios de cine norteamericanos. Su principal rama de producción y distribución de películas es Universal Pictures. Está controlada por una sociedad compuesta por General Electric y Vivendi SA. llamada NBC Universal.');
INSERT INTO "DISTRIBUCION_COMP" VALUES (10, 'United Artists', NULL);
INSERT INTO "DISTRIBUCION_COMP" VALUES (11, 'Commercial Pictures', NULL);
INSERT INTO "DISTRIBUCION_COMP" VALUES (12, 'Celfin Capital', NULL);
INSERT INTO "DISTRIBUCION_COMP" VALUES (13, 'Loew''s', NULL);
INSERT INTO "DISTRIBUCION_COMP" VALUES (14, 'Warner Bros', 'Warner Brothers Entertainment, Inc es uno de los más grandes productores de cine y televisión del mundo. Es actualmente una filial del conglomerado Time Warner con sede en Burbank, California, Estados Unidos. Warner Bros. incluye varias compañías subsidiarias, entre ellas Warner Bros. Studios, Warner Bros. Pictures, Warner Bros. Interactive Entertainment, Warner Bros. Television, Warner Bros. Animation, Warner Home Video, New Line Cinema, Castle Rock Entertainment, Turner Entertainment, Dark Castle Entertainment, DC Comics, y los remanentes de Hanna-Barbera Cartoons, Inc., aunque el antiguo estudio de la Hanna-Barbera es ahora conocido como Cartoon Network Studios y está bajo la Turner Broadcasting.');
INSERT INTO "DISTRIBUCION_COMP" VALUES (15, 'Island Alive', NULL);
INSERT INTO "DISTRIBUCION_COMP" VALUES (16, 'Toho', NULL);
INSERT INTO "DISTRIBUCION_COMP" VALUES (17, 'Walt Disney Pictures', 'The Walt Disney Company S.A. (también conocida como Disney Enterprises, Inc. simplemente Disney o Grupo Disney S.A.) es uno de las compañías de medios de comunicación y entretenimiento más grandes del mundo. Fundada el 16 de octubre de 1923 por Walt Disney y Roy Disney como un estudio de animación, al paso del tiempo se convertiría en uno de los estudios de Hollywood.');
INSERT INTO "DISTRIBUCION_COMP" VALUES (18, 'Earthworks Productions', NULL);
INSERT INTO "DISTRIBUCION_COMP" VALUES (19, 'Almi Pictures', NULL);
INSERT INTO "DISTRIBUCION_COMP" VALUES (20, 'Koch Lorber Films', NULL);
INSERT INTO "DISTRIBUCION_COMP" VALUES (21, 'Orion Pictures', 'Orion Pictures Corporation fue una compañía de Hollywood formada por 3 ejecutivos de United Artists, una pequeña empresa con una larga reputación. Orion gano fama por haber producido las películas de Woody Allen, y aunque había ganado varios Oscar por sus filmes, cayó rápidamente en una enorme deuda en los ''90, luego de haber salido de la quiebra, la compañía fundió tras haber sido vendida a Metro-Goldwyn-Mayer. Fue la empresa productora de las películas de Terminator y Robocop.');
INSERT INTO "DISTRIBUCION_COMP" VALUES (22, 'National Film Board of Canada', NULL);
INSERT INTO "DISTRIBUCION_COMP" VALUES (23, 'The Cannon Group Inc', 'The Cannon Group Inc. was a group of companies including Cannon Films which produced a distinctive line of low to medium budget films from 1967 to 1993. The extensive group also owned amongst others, a large international cinema chain and a video film company which invested heavily in the video market, buying the international video rights to several classic film libraries.');
INSERT INTO "DISTRIBUCION_COMP" VALUES (24, 'Bud Yorkin Productions', NULL);
INSERT INTO "DISTRIBUCION_COMP" VALUES (25, 'Island Pictures', NULL);
