CREATE OR REPLACE TRIGGER validarTipo
BEFORE INSERT ON tipo
FOR EACH ROW

BEGIN

	IF (:NEW.temperatura IS NULL) THEN
		raise_application_error(-20006,'AL INSERTAR UN TIPO DE CERVEZA DEBE TENER SU TEMPERATURA IDEAL');
	END IF;

	IF (:NEW.temperatura.valor IS NULL) OR (:NEW.temperatura.unidad IS NULL) THEN
		raise_application_error(-20006,'AL INSERTAR UN TIPO DE CERVEZA EN LA TEMPERATURA NO SE PUEDE DEJAR EN NULL EL CAMPO VALOR NI UNIDAD');
	END IF;

	IF (:NEW.temperatura.unidad <> 'CENTIGRADO' ) THEN
		raise_application_error(-20006,'AL INSERTAR UN TIPO LA UNIDAD DE LA TEMPERATURA NO PUEDE SER OTRA COSA QUE NO SEA CENTIGRADO');
	END IF;

	IF (:NEW.alimentos IS NULL) THEN
		raise_application_error(-20006,'AL INSERTAR UN TIPO DEBE TENER ALMENOS UN ALIMENTO');
	END IF;

	FOR i IN 1..:NEW.alimentos.COUNT LOOP
		IF (:NEW.alimentos(i) IS NULL ) THEN
			raise_application_error(-20006,'AL INSERTAR UN TIPO VECTOR DE ALIMENTOS NO PUEDE CONTENER NULL');
		END IF;
	END LOOP;

END;
