DROP TABLE LUGAR CASCADE CONSTRAINT;
DROP TABLE PROVEEDOR CASCADE CONSTRAINT;
DROP TABLE TIPO CASCADE CONSTRAINT;
DROP TABLE EMPRESA CASCADE CONSTRAINT;
DROP TABLE CERVEZA_CATALOGO CASCADE CONSTRAINT;
DROP TABLE PRESENTACION CASCADE CONSTRAINT;
DROP TABLE PRESENTACION_has_LUGAR CASCADE CONSTRAINT;
DROP TABLE PROCESO CASCADE CONSTRAINT;
DROP TABLE FABRICA CASCADE CONSTRAINT;
DROP TABLE PEDIDO CASCADE CONSTRAINT;
DROP TABLE MATERIA_PRIMA CASCADE CONSTRAINT;
DROP TABLE VARIEDAD CASCADE CONSTRAINT;
DROP TABLE VARIEDAD_has_LUGAR CASCADE CONSTRAINT;
DROP TABLE MATERIA_PRIMA_has_PROCESO CASCADE CONSTRAINT;
DROP TABLE CATALOGO_MATERIA CASCADE CONSTRAINT;
DROP TABLE EQUIPO CASCADE CONSTRAINT;
DROP TABLE EQUIPO_has_PROCESO CASCADE CONSTRAINT;
DROP TABLE CATALOGO_EQUIPOS CASCADE CONSTRAINT;
DROP TABLE PEDIDO_has_CATALOGO CASCADE CONSTRAINT;
DROP TABLE PRODUCCION CASCADE CONSTRAINT;
DROP TABLE DESCUENTO_PEDIDO CASCADE CONSTRAINT;
DROP TABLE BAR CASCADE CONSTRAINT;
DROP TABLE HISTORIA CASCADE CONSTRAINT;
DROP TABLE TOUR CASCADE CONSTRAINT;
DROP TABLE FABRICA_has_TOUR CASCADE CONSTRAINT;
DROP TABLE GRUPO_TOUR CASCADE CONSTRAINT;
DROP TABLE ENTRADA CASCADE CONSTRAINT;
DROP TABLE EVENTO CASCADE CONSTRAINT;
DROP TABLE EMPRESA_has_EVENTO CASCADE CONSTRAINT;
DROP TABLE ELABORACION CASCADE CONSTRAINT;

drop type nt_reqadq;
drop type nt_contacto;
drop type nt_telefonos;
drop type nt_horario;
drop type nt_descuento;
drop type t_regla;
drop type t_infnutricional;
drop type t_color;
drop type t_rangoedad;
drop type t_temperatura;
drop type v_alimento;
drop type v_feriado;
drop type v_temporada;
drop type v_requisito;
drop type v_formapago;
drop type nt_historia;
drop type nt_pagweb;
drop type nt_presentacion;
drop type nt_fdist;
drop type t_contacto;
drop type t_descuento;
drop type t_formadist; 
drop type t_historia;
drop type t_horario;
drop type t_paginaweb;
drop type t_presentacion;
drop type t_reqad;
drop type v_telefono;
drop type t_telefono; 

drop sequence "S_LUGAR";
drop sequence "S_BAR";
drop sequence "S_HISTORIA";
drop sequence "S_CERVEZA";
drop sequence "S_VARIEDAD";
drop sequence "S_MATERIA_PRIMA";
drop sequence "S_PRESENTACION";
drop sequence "S_TIPO";
drop sequence "S_EMPRESA";
drop sequence "S_PRODUCCION";
drop sequence "S_FABRICA";
drop sequence "S_DESCUENTO";
drop sequence "S_PEDIDO_CATALOGO";
drop sequence "S_PEDIDO";
drop sequence "S_CATALOGO_MATERIA";
drop sequence "S_EVENTO";
drop sequence "S_TOUR";
drop sequence "S_PROVEEDOR";
drop sequence "S_PROCESO";
drop sequence "S_EQUIPO";
drop sequence "S_ENTRADA";
drop sequence "S_CATALOGO_EQUIPO";
drop sequence "S_GRUPO_TOUR";
drop sequence "S_EMPRESA_EVENTO";